
- hosts: web
  become: yes
  tasks:
    - name: Install Node Exporter
      shell: |
        useradd --no-create-home --shell /bin/false node_exporter || true
        curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        tar -xvf node_exporter-1.7.0.linux-amd64.tar.gz
        cp node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/
        chown node_exporter:node_exporter /usr/local/bin/node_exporter
        tee /etc/systemd/system/node_exporter.service <<EOF
        [Unit]
        Description=Node Exporter
        After=network.target

        [Service]
        User=node_exporter
        ExecStart=/usr/local/bin/node_exporter

        [Install]
        WantedBy=default.target
        EOF

    - name: Start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
