name: Deploy Infra and Configure Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_key_name: "my-key"
      TF_VAR_public_key: "${{ secrets.SSH_PUBLIC_KEY }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # ou autre version compatible

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false -lock=false

      - name: Get instance IP and export as output
        id: instance_ip
        working-directory: terraform
        run: |
          ip=$(terraform output -raw instance_ip)
          echo "instance_ip=$ip" >> $GITHUB_OUTPUT

      - name: Afficher l'adresse IP
        run: echo "Adresse IP de l'instance EC2 : ${{ steps.instance_ip.outputs.instance_ip }}"

      - name: Installer Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Exécuter le playbook Ansible
        working-directory: ansible
        run: |
          ansible-playbook -i inventory/hosts.ini playbook.yml
