name: Deploy Infra and Configure Server

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_key_name: "my-key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: terraform

      - name: Extract EC2 Public IP
        id: get_ip
        run: |
          cd terraform
          IP=$(terraform output -raw instance_ip | tr -d '\r\n ')
          echo "INSTANCE_IP=$IP" >> $GITHUB_ENV
          echo "instance_ip=$IP" >> $GITHUB_OUTPUT
          echo "✔️ Public IP extracted: $IP"

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Create Ansible inventory
        run: |
          mkdir -p ansible/inventory
          cat <<EOF > ansible/inventory/hosts.ini
          [web]
          ${{ env.INSTANCE_IP }} ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_connection=ssh ansible_ssh_private_key_file=${SSH_AUTH_SOCK:+agent} ansible_python_interpreter=/usr/bin/python3
          EOF
          echo "✔️ Inventory generated:"
          cat ansible/inventory/hosts.ini

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Prometheus playbook
        run: ansible-playbook ansible/playbooks/prometheus_node_exporter.yml -i ansible/inventory/hosts.ini

      - name: Run Grafana playbook
        run: ansible-playbook ansible/playbooks/grafana_prometheus.yml -i ansible/inventory/hosts.ini
