name: Deploy Infra and Configure Server

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_key_name: "ansible-key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: terraform

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          echo "Fetching EC2 IP..."
          IP=$(terraform -chdir=terraform output -raw instance_ip)
          CLEAN_IP=$(echo "$IP" | tr -d '\r\n' | xargs)
          echo "INSTANCE_IP=$CLEAN_IP" >> $GITHUB_ENV
          echo "ip=$CLEAN_IP" >> $GITHUB_OUTPUT
          echo "EC2 IP: $CLEAN_IP"

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts
          echo "✅ SSH configured."

      - name: Test SSH Access
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ env.INSTANCE_IP }} "echo '✅ SSH OK'"

      - name: Create Ansible Inventory
        run: |
          mkdir -p ansible/inventory
          echo "[web]" > ansible/inventory/hosts.ini
          echo "${{ env.INSTANCE_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> ansible/inventory/hosts.ini
          echo "📄 Inventory content:"
          cat ansible/inventory/hosts.ini

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Prometheus Playbook
        run: ansible-playbook ansible/playbooks/prometheus_node_exporter.yml -i ansible/inventory/hosts.ini

      - name: Run Grafana Playbook
        run: ansible-playbook ansible/playbooks/grafana_prometheus.yml -i ansible/inventory/hosts.ini
