name: Deploy Infra and Configure Server

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_key_name: ${{ secrets.SSH_KEY_NAME }} # si tu passes le nom de la key

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Generate Ansible Inventory
        run: |
          mkdir -p ansible/inventory
          echo "[web]" > ansible/inventory/hosts.ini
          echo "$(terraform output -raw instance_ip) ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory/hosts.ini
        working-directory: terraform

      - name: Install Ansible Dependencies
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook for Prometheus
        run: ansible-playbook ansible/playbooks/prometheus_node_exporter.yml -i ansible/inventory/hosts.ini

      - name: Run Ansible Playbook for Grafana
        run: ansible-playbook ansible/playbooks/grafana_prometheus.yml -i ansible/inventory/hosts.ini
