name: Deploy Infra and Configure Server

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_key_name: "ansible-key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: terraform

      - name: Get EC2 public IP
        id: get_ip
        run: |
          IP=$(terraform -chdir=terraform output -raw instance_ip | tr -d '\r\n' | xargs)
          echo "INSTANCE_IP=$IP" >> $GITHUB_ENV
          echo "Got IP: $IP"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Create Ansible inventory
        run: |
          mkdir -p ansible/inventory
          echo "[web]" > ansible/inventory/hosts.ini
          echo "${{ env.INSTANCE_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> ansible/inventory/hosts.ini
          cat ansible/inventory/hosts.ini

      - name: Wait for SSH availability
        run: |
          for i in {1..30}; do
            nc -z -w 5 ${{ env.INSTANCE_IP }} 22 && echo "SSH is available" && exit 0
            echo "Waiting for SSH..."
            sleep 10
          done
          echo "SSH connection timed out"
          exit 1

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Prometheus playbook
        run: ansible-playbook ansible/playbooks/prometheus_node_exporter.yml -i ansible/inventory/hosts.ini

      - name: Run Grafana playbook
        run: ansible-playbook ansible/playbooks/grafana_prometheus.yml -i ansible/inventory/hosts.ini
