name: Deploy Infra and Configure Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_key_name: "my-key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH public key to file
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./terraform/id_rsa.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_public_key_path: "./terraform/id_rsa.pub"
        run: terraform apply -auto-approve

      - name: Get instance IP
        id: instance_ip
        working-directory: terraform
        run: echo "instance_ip=$(terraform output -raw instance_ip)" >> $GITHUB_OUTPUT

      - name: Restore SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Create Ansible inventory
        run: |
          mkdir -p ansible/inventory
          echo "[web]" > ansible/inventory/hosts.ini
          echo "${{ steps.instance_ip.outputs.instance_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory/hosts.ini

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml -i ansible/inventory/hosts.ini
